# Generated by Django 6.1.1 on 2026-09-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='attendees',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
