# Generated by Django 6.1.1 on 2026-10-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_booking_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='attendees',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_by',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
